version: '3'
services: 
    jenkins:
        build:
            dockerfile: dockerfile
            context: ./jenkins_ansible
        ports: 
            - "4001:8080"
        volumes: 
            - ./jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock  
        networks: 
            - net

    remotehost:
        build: 
            dockerfile: dockerfile
            context: ./centos
        container_name: opensshServer
        networks: 
            - net  
    db_host:
        container_name: db_host
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=1234
        networks: 
            - net
        volumes: 
            - ./db_data:/var/lib/mysql
networks: 
    net:
        
