version: '3'
services: 
    jenkins:
        image: 'jenkins/jenkins:lts'
        ports: 
            - "4000:8080"
        volumes: 
            - ./jenkins_home:/var/jenkins_home
        networks: 
            - net
networks: 
    net:
        